---
title: "Murrelet & Raven Detection Models"
author: "Tam Ta & Amelia J. DuVall"
date: "4/13/2022"
output: pdf_document
---

# TODO
# chunk time in periods (dawn/dusk)
## dawn period (00:00-07:00), day (07:01-17:00), dusk period (17:01-11:59)
# create camera ID for random effect (cam 1-7)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## load libraries
library(tidyverse)
library(here)
library(lme4)

## load data
camera_full <- read.csv(here("data", "camera_dat_all_images.csv")) 
camera_set <- read.csv(here("data", "camera_dat_image_set.csv")) 
camera_hourly <- read.csv(here("data", "camera_hourly_det.csv"))
acoustic <- read.csv(here("data", "acoustic", "acoustic_dat.csv")) 
```

## Model #1: SCMU Camera Detections

```{r mod1}
# test <- camera_hourly %>%
#   mutate(tod = ifelse(tod == "day", "aday", tod))
# m1 <- glmer(SCMU_hourly_det ~ image_type + tod + jday + jday^2 + (1 | cam_id), 
#             data = test, family = binomial)

m1 <- glmer(SCMU_hourly_det ~ image_type + tod + jday + jday^2 + (1 | cam_id), 
            data = camera_hourly, family = binomial)
summary(m1)

## day of year as a quadratic
# plot(camera_hourly$jday, camera_hourly$jday) 
# plot(camera_hourly$jday, camera_hourly$jday + camera_hourly$jday^2)
# plot(camera_hourly$jday, (-0.14*camera_hourly$jday +  ((-0.14^2)*camera_hourly$jday^2)))
```

## Model #2: CORA Camera Detections
```{r mod2}
m2 <- glmer(CORA_hourly_det ~ image_type + tod + jday + jday^2 + (1 | cam_id), 
            data = camera_hourly, family = binomial)
summary(m2)

```
